from PyQt6.QtWidgets import QWidget, QVBoxLayout, QLabel
from PyQt6.QtGui import QColor, QPalette

class NoteItem(QWidget):
    def __init__(self, title, content, color, tags="", pinned=False, archived=False, reminder=None, attached_files=None, collaborators=None, drawing=""):
        super().__init__()
        layout = QVBoxLayout()
        self.title_label = QLabel(title)
        self.title_label.setObjectName("noteTitle")
        self.content_label = QLabel(content[:50] + "..." if len(content) > 50 else content)
        self.content_label.setObjectName("noteContent")
        self.tags_label = QLabel(f"Tags: {tags}" if tags else "Tags: None")
        self.tags_label.setObjectName("noteTags")
        self.status_label = QLabel(f"{'Pinned' if pinned else ''}{' Archived' if archived else ''}")
        self.status_label.setObjectName("noteStatus")
        self.reminder_label = QLabel(f"Reminder: {reminder.toString('yyyy-MM-dd HH:mm') if reminder else 'None'}")
        self.reminder_label.setObjectName("noteReminder")
        self.files_label = QLabel(f"Attachments: {', '.join(attached_files) if attached_files else 'None'}")
        self.files_label.setObjectName("noteFiles")
        self.collaborators_label = QLabel(f"Collaborators: {', '.join(collaborators) if collaborators else 'None'}")
        self.collaborators_label.setObjectName("noteCollaborators")
        self.drawing_label = QLabel(f"Drawing: {drawing if drawing else 'None'}")
        self.drawing_label.setObjectName("noteDrawing")
        layout.addWidget(self.title_label)
        layout.addWidget(self.content_label)
        layout.addWidget(self.tags_label)
        layout.addWidget(self.status_label)
        layout.addWidget(self.reminder_label)
        layout.addWidget(self.files_label)
        layout.addWidget(self.collaborators_label)
        layout.addWidget(self.drawing_label)
        self.setLayout(layout)
        self.setAutoFillBackground(True)
        palette = self.palette()
        palette.setColor(QPalette.ColorRole.Window, QColor(color))
        self.setPalette(palette)
        self.setObjectName("noteItem")